---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-python
  labels:
    app: oidc-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-python
  template:
    metadata:
      labels:
        app: oidc-python
    spec:
      containers:
      - name: oidc-python
        image: oidc-python:1.0.1
        env:
        - name: FLASK_ENV
          value: development
        - name: DEBUG
          value: "True"
        - name: SERVER_NAME
          value: oidc-python.com
        - name: PREFERRED_URL_SCHEME
          value: http
        - name: OIDC_ISSUER
          value: https://idp-eval.u.washington.edu
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      volumes:
      - name: secrets
        secret:
          secretName: oidc-python